turbine:
  aggregator:
    cluster-config: default
  # 配置 Eureka 中的 serviceId 列表，指定要监控的服务，多个服务用“,”隔开
  app-config: lion-zuul-server,lion-auth,lion-upms,lion-demo-provider,lion-demo-consumer,lion-demo-ribbon,lion-demo-sample
  # 指定集群名称
  cluster-name-expression: new String("default")
  combine-host-port: true