#server:
#  port: 8802
#
#spring:
#  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8080
#  rabbitmq:
#    host: 192.168.1.200
#    port: 5672
#    username: admin
#    password: admin
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: rabbit
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always